// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Enrich telemetry attributes with compliance control data
	// (POST /v1/enrich)
	PostV1Enrich(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostV1Enrich operation middleware
func (siw *ServerInterfaceWrapper) PostV1Enrich(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1Enrich(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/enrich", wrapper.PostV1Enrich)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RYa2/buBL9KwTvBW4LyI+k94V8c512a6BtvHG6wKIJFrQ4ltlIpEqOnBqB//tiSMl6",
	"OmnR3W+xRM6cmTkzc5RHHpssNxo0On7xyF28hUz4P+cmy1MldAz0S4KLrcpRGc0vGu+YBBQqdWxjTcau",
	"5qu3bAVxYRXu2dxotCZlS2s2KoUxj3huTQ4WFXgXcThAf/7TwoZf8H9MajyTEsyk9lZa5IeIg7Yq3mag",
	"cYUCC9cHGZ4zs2G4BRbXkOurLLcmBuc42SsyfvGZr4q4fPJJZyLPQfKIL4VFJVL/8F6bB80jvrpX/u1d",
	"xOGbyPIUyOfxNu5zeuDQKp0Q4I0VGTwYe+++P9639Z1DxK1y999/95pOH+gafC2UBUnRVRlvwRlI5t0x",
	"ALP+AjGS+34Z+imvSl/6YUpvjM0EvWYbY5tVEM6Bc+SzxwuR56mKxVqlCvd9L2/0Tlmj6apj3qhG+IaO",
	"PWzBAsOtckcA3hT4GKsifeZLa2QRe2sR0SShEt1FXCFkHkCveOUDYa3Y0+9YoEhNspB9dJ+0+loAUxI0",
	"qo0C6wMnCrpudkorFMOxHE2k/Gq1XI1eD7EpFgiJsQPZmZdvvFWRqXTPcCtwGMEaUqMTx9C0/M48i6sG",
	"HvKvfi7yNSidlBTwHdaJ+dfZaPq/8fRsyLWFDKTynLps+u/CabyshoCF2GQZaAmSNcwwh5ayti8B1/xp",
	"IbuGzOyAWWOQFQ4sEyFNQkum6Ew1UnKwbDH7wHKTqjiwrxNFpy0VpaDmVKO8Tzfi29ZMOTmjj+TyUEvH",
	"HmyjP3tduHnC+DUkRSqwpJnSsnBo98yh0FJY6coCw06khUCQneZvt+PHxepm9P/pdPSfV9SPV/PR+Y91",
	"YyOipxPRCv1I03J5EUHqmLsRtCHP5iPi5nz+3/HZj2Dt1L01hFtRPF3363ITnA5UufvGhH2yzinsYGCW",
	"kw/m35EhEytfxweFW6aNHrWLWS7PuVWoYr8o36lkyyP+AaQqMh7x9+aBR3xR4xBpe3WWF55ulIB1KDlv",
	"jivsGr4W4HCItP4Fy8U+NSJwEoHalrgrEK1aF9jUB71c+Y7eP7eEl+FUF3x5+Tn0LjfanRJdgC0pkwEK",
	"KVAwpeO0kMTYasSSeFE6cVGD1FGXGOMmrYMYrDVfQ551NvLpFdpYjPX2qpdVf7MoOTDzT434nxjBg5Kx",
	"odfa06756+SAao+d7lBoCLaywwLFD0SLrg5upv375N2AtDu+GmSYtcZ6CndcywGqvbu5WdIwJ/3sTzRY",
	"8u/pNOKhi/kFVxpfnddtqzRCApYcZuCcSAaMeySsev1cx5fuq+NDoS2PTXmiYWBHwz4GRmLLz/rQigx0",
	"ojQE+gxKU4bGpO7EGHjjb38U2UCQ9LRSHS1nQYzlYCmFIP2Bcsl4oWIZ0IyMA5NF1WINfbScDami4OS6",
	"SOHHRGkJzhYp9JZ2DaYt0STo/Yh6cEQ9+GwJe9nqoO3XlCzQyuoHMtPsar44bh9kFhLltUenho2PPAd2",
	"p0gGGct+gUxYET4ZNI5v9dIaYocjs+ySTNESoFKscojZ7pyBlrlR9K1BBqRysdmB9fpVSybNg6ZtonRy",
	"q4/WjzB+n314z14khZL0M6okv4uOk+klE8E5fWNuRIwu8obFrR4Op8Lj4VzloG+OOyw2aQoxekmGkFjP",
	"qfEtEQgV+tqVEOchAWxV5ma2XPCI78C6kOfp+Gw8JV6ZHLTIFb/gr8bTMc2/XODWd8FkdzYJuEJPDO1c",
	"mvc5OiaYA6SGuIf90NJ17AWMk3Hkew/Z4jKqmKlFBlEY9ovLl5SaW20BC6sdE1KqoCUaOR9ZSD19G8bX",
	"whGftc+LpfPSZEJpmggqHt/qGxL9x8wq5w/67wQ0bA0sFmkKkq2JZ52kz6uk/8uxuHBI4yX8W8HYkHsa",
	"Hb4Ufi0ujcPfzsLGL2UfOHxt5L5auqQ86qVLFydfXPjECYvguTXRF0OHdlOiLcA/CGLDl/N8Ov1bAJR6",
	"xiPo/LsgbN9Nkab7kuGtsnF/YyOKFP86ZH4PDoD5pOFbDjERB8ozEXdFlgkvXEJEw9T1orjRrJUEI2VG",
	"rScSrw8auvKOjE925xN+8Vj+9Uc5Guonj0T9w2SdmrWbPEqVgMND73UmtNqAQzd5tLABS4uuf4owTFLl",
	"W/RwOPwZAAD//69tzYH4EwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
