// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

// Defines values for ComplianceEnrichmentStatus.
const (
	Partial  ComplianceEnrichmentStatus = "Partial"
	Skipped  ComplianceEnrichmentStatus = "Skipped"
	Success  ComplianceEnrichmentStatus = "Success"
	Unknown  ComplianceEnrichmentStatus = "Unknown"
	Unmapped ComplianceEnrichmentStatus = "Unmapped"
)

// Valid indicates whether the value is a known member of the ComplianceEnrichmentStatus enum.
func (e ComplianceEnrichmentStatus) Valid() bool {
	switch e {
	case Partial:
		return true
	case Skipped:
		return true
	case Success:
		return true
	case Unknown:
		return true
	case Unmapped:
		return true
	default:
		return false
	}
}

// Defines values for ComplianceRiskLevel.
const (
	Critical      ComplianceRiskLevel = "Critical"
	High          ComplianceRiskLevel = "High"
	Informational ComplianceRiskLevel = "Informational"
	Low           ComplianceRiskLevel = "Low"
	Medium        ComplianceRiskLevel = "Medium"
)

// Valid indicates whether the value is a known member of the ComplianceRiskLevel enum.
func (e ComplianceRiskLevel) Valid() bool {
	switch e {
	case Critical:
		return true
	case High:
		return true
	case Informational:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for OCIErrorCode.
const (
	BLOBUNKNOWN     OCIErrorCode = "BLOB_UNKNOWN"
	MANIFESTUNKNOWN OCIErrorCode = "MANIFEST_UNKNOWN"
	NAMEUNKNOWN     OCIErrorCode = "NAME_UNKNOWN"
)

// Valid indicates whether the value is a known member of the OCIErrorCode enum.
func (e OCIErrorCode) Valid() bool {
	switch e {
	case BLOBUNKNOWN:
		return true
	case MANIFESTUNKNOWN:
		return true
	case NAMEUNKNOWN:
		return true
	default:
		return false
	}
}

// Defines values for OCILayerDescriptorMediaType.
const (
	ApplicationvndGemaraCatalogV1Yaml  OCILayerDescriptorMediaType = "application/vnd.gemara.catalog.v1+yaml"
	ApplicationvndGemaraGuidanceV1Yaml OCILayerDescriptorMediaType = "application/vnd.gemara.guidance.v1+yaml"
	ApplicationvndGemaraPolicyV1Yaml   OCILayerDescriptorMediaType = "application/vnd.gemara.policy.v1+yaml"
)

// Valid indicates whether the value is a known member of the OCILayerDescriptorMediaType enum.
func (e OCILayerDescriptorMediaType) Valid() bool {
	switch e {
	case ApplicationvndGemaraCatalogV1Yaml:
		return true
	case ApplicationvndGemaraGuidanceV1Yaml:
		return true
	case ApplicationvndGemaraPolicyV1Yaml:
		return true
	default:
		return false
	}
}

// Compliance Compliance details from OCSF Security Control Profile.
type Compliance struct {
	// Control Security control information for compliance assessment
	Control ComplianceControl `json:"control"`

	// EnrichmentStatus Status of the compliance enrichment process
	EnrichmentStatus ComplianceEnrichmentStatus `json:"enrichmentStatus"`

	// Frameworks Compliance framework and requirement information
	Frameworks ComplianceFrameworks `json:"frameworks"`

	// Risk Compliance risk assessment information
	Risk *ComplianceRisk `json:"risk,omitempty"`
}

// ComplianceEnrichmentStatus Status of the compliance enrichment process
type ComplianceEnrichmentStatus string

// ComplianceControl Security control information for compliance assessment
type ComplianceControl struct {
	// Applicability Environments or contexts where this control applies
	Applicability *[]string `json:"applicability,omitempty"`

	// CatalogId Unique identifier for the security control catalog or framework
	CatalogId string `json:"catalogId"`

	// Category Category or family that the security control belongs to
	Category string `json:"category"`

	// Id Unique identifier for the security control being assessed
	Id string `json:"id"`

	// RemediationDescription Description of the recommended remediation strategy for this control
	RemediationDescription *string `json:"remediationDescription,omitempty"`
}

// ComplianceFrameworks Compliance framework and requirement information
type ComplianceFrameworks struct {
	// Frameworks Regulatory or industry standards being evaluated for compliance
	Frameworks []string `json:"frameworks"`

	// Requirements Compliance requirement identifiers from the frameworks being evaluated
	Requirements []string `json:"requirements"`
}

// ComplianceRisk Compliance risk assessment information
type ComplianceRisk struct {
	// Level Risk level associated with non-compliance
	Level ComplianceRiskLevel `json:"level"`
}

// ComplianceRiskLevel Risk level associated with non-compliance
type ComplianceRiskLevel string

// EnrichmentRequest Request payload for telemetry attribute enrichment
type EnrichmentRequest struct {
	// Policy Complete evidence log from policy engines and compliance assessment tools
	Policy Policy `json:"policy"`
}

// EnrichmentResponse Complete compliance metadata including control mappings, frameworks, risk assessment.
type EnrichmentResponse struct {
	// Compliance Compliance details from OCSF Security Control Profile.
	Compliance Compliance `json:"compliance"`
}

// Error defines model for Error.
type Error struct {
	// Code HTTP status code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// OCIDescriptor An OCI content descriptor (used for config blobs).
type OCIDescriptor struct {
	// Digest Content-addressable digest (e.g. sha256:...).
	Digest string `json:"digest"`

	// MediaType Media type of the referenced content.
	MediaType string `json:"mediaType"`

	// Size Size of the content in bytes.
	Size int64 `json:"size"`
}

// OCIError A single OCI error entry.
type OCIError struct {
	// Code OCI error code. One of: NAME_UNKNOWN, MANIFEST_UNKNOWN,
	// BLOB_UNKNOWN.
	Code OCIErrorCode `json:"code"`

	// Detail Optional additional error context.
	Detail interface{} `json:"detail,omitempty"`

	// Message Human-readable error message.
	Message string `json:"message"`
}

// OCIErrorCode OCI error code. One of: NAME_UNKNOWN, MANIFEST_UNKNOWN,
// BLOB_UNKNOWN.
type OCIErrorCode string

// OCIErrors OCI Distribution Spec error response.
type OCIErrors struct {
	Errors []OCIError `json:"errors"`
}

// OCILayerDescriptor An OCI layer descriptor for Gemara content. The mediaType field
// identifies the Gemara layer type of the referenced YAML file.
type OCILayerDescriptor struct {
	// Digest Content-addressable digest (e.g. sha256:...).
	Digest string `json:"digest"`

	// MediaType The Gemara content type of this layer. Identifies which Gemara
	// layer the YAML content belongs to.
	MediaType OCILayerDescriptorMediaType `json:"mediaType"`

	// Size Size of the content in bytes.
	Size int64 `json:"size"`
}

// OCILayerDescriptorMediaType The Gemara content type of this layer. Identifies which Gemara
// layer the YAML content belongs to.
type OCILayerDescriptorMediaType string

// OCIManifest An OCI image manifest describing layers of Gemara compliance content.
type OCIManifest struct {
	// Config An OCI content descriptor (used for config blobs).
	Config OCIDescriptor `json:"config"`

	// Layers Ordered list of layer descriptors. Each layer contains one Gemara YAML file.
	Layers []OCILayerDescriptor `json:"layers"`

	// MediaType The manifest media type.
	MediaType string `json:"mediaType"`

	// SchemaVersion Must be 2 for OCI image manifests.
	SchemaVersion int `json:"schemaVersion"`
}

// Policy Complete evidence log from policy engines and compliance assessment tools
type Policy struct {
	// PolicyEngineName Name of the policy engine that performed the evaluation or enforcement action
	PolicyEngineName string `json:"policyEngineName"`

	// PolicyRuleId Unique identifier for the policy rule being evaluated or enforced
	PolicyRuleId string `json:"policyRuleId"`
}

// PostV1EnrichJSONRequestBody defines body for PostV1Enrich for application/json ContentType.
type PostV1EnrichJSONRequestBody = EnrichmentRequest
